language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
services:
  - docker
env:
  global:
    - HDF5_VERSION=1.10.1
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
addons:
  apt:
    update: true
    packages:
    - libhdf5-dev
before_install:
  - source <( curl --insecure https://raw.githubusercontent.com/hhoeflin/hdf5r/master/travis_setup.sh | sed "s/hdf5r/dynwrap/" )
install:
 - if [ `git branch | grep '* master' | wc -l` == 0 ]; then sed -i 's#\(dynverse/[^, ]*\)#\1@devel#' DESCRIPTION; fi
 - R -e 'if ("devtools" %in% rownames(installed.packages())) update.packages(oldPkgs = "devtools", ask = FALSE) else install.packages("devtools")'
 - R -e 'devtools::install_cran("covr")'
 - R -e 'setRepositories(ind = 1:2)'
 - R -e 'devtools::install(dependencies = T, upgrade = T)'
after_success:
 - R -e 'covr::codecov()'
script:
 - echo No R CMD check since this is an init.
after_success:
 - echo Init 0 succeeded!
