language: r
sudo: required
dist: trusty
bioc_required: true
cache:
  directories:
    - $HOME/.cache/hdf5
    - $HOME/R/Library
services:
  - docker
before_install:
  - export HDF5_DIR=$HOME/.cache/hdf5
  - echo $HDF5_DIR
  - export HDF5_VERSION=1.10.1
  - echo $HDF5_VERSION
  - source get_hdf5_if_needed.sh
  - ls -lRa $HDF5_DIR
install:
 - if [ `git branch | grep '* master' | wc -l` == 0 ]; then sed -i 's#\(dynverse/[^, ]*\)#\1@devel#' DESCRIPTION; fi
 - R -e 'if ("devtools" %in% rownames(installed.packages())) update.packages(oldPkgs = "devtools", ask = FALSE) else install.packages("devtools")'
 - R -e 'devtools::install_cran("covr")'
script:
 - echo No R CMD check since this is an init.
after_success:
 - echo Init 0 succeeded!
