language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
env:
  - R_MAX_NUM_DLLS=250
install:
 - R -e 'install.packages("devtools")'
 - R -e 'setRepositories(ind = 1:2)'
 - R -e 'devtools::install(dependencies = T, upgrade = T)'
