---
title: "Adding a new TI method using docker"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Adding a new TI method using docker}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

This vignette describes how to include your own method into the dynverse workflow. We'll illustrate this with a very basic method: using one of the components of a PCA as the pseudotimes.

There are two main ways to add a new method:

* **Directly within R**. In this case you create an R function or R packages. The user will have to install all dependencies. This is the use case described here.
* **Using a docker**. In this case you create a docker which uses some input files (eg. a file containing the expression) and returns some output files. This use case is described here.

A TI docker requires at least three files:

* A definition yaml or json file, used to determine the format of input, output and parameters.
* A Dockerfile, used to construct the docker.
* Script(s) to load the data, run the method, and save the output

Although not required, it can be very useful to 

## Method definition file

The complete definition file for this example can be found
