---
title: "Transferring files from and to the docker"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Transferring files from and to the docker}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, echo=FALSE, message=FALSE}
library(dplyr)
library(readr)
library(purrr)
library(dynwrap)
# devtools::load_all()
```

```{r}
# # generate tasks
# n_genes <- 10
# tasks <- map(round(seq(10, 10, length.out = 1)), function(n_cells) {
#   expression <- matrix(runif(n_cells * n_genes), nrow=n_cells, ncol = n_genes)
#   rownames(expression) <- paste0("C", seq_len(n_cells))
#   colnames(expression) <- paste0("G", seq_len(n_genes))
#   wrap_expression(expression, expression)
# })
# task_design <- tibble(
#   task = tasks,
#   n_cells = map_int(tasks, ~nrow(.$expression))
# ) %>% 
#   mutate(task_ix = row_number())
# 
# # methods
# input_formats <- formals(dynwrap:::save_inputs)$input_format %>% eval
# output_formats <- formals(dynwrap:::wrap_output)$output_format %>% eval
# definition <- extract_definition_from_docker_image("dynverse/clustermst")
# method_design <- crossing(
#   tibble(input_format = input_formats),
#   tibble(output_format = output_formats),
# ) %>%
#   mutate(
#     method = pmap(., function(input_format, output_format, ...) {
#       definition$output$format <- output_format
#       definition$input$format <- input_format
#       create_docker_ti_method("dynverse/clustermst", definition)()
#   }),
#   method_ix = row_number()
# )
# 
# # do TI
# output <- infer_trajectories(tasks, method_design$method)
# models <- output %>%
#   left_join(task_design %>% select(task_ix, n_cells), "task_ix") %>%
#   left_join(method_design, "method_ix") %>%
#   mutate(time = map_dbl(summary, "time_method"))
# 
# # plot
# models %>% 
#   filter(n_cells == max(n_cells)) %>% 
#   ggplot(aes(input_format, output_format)) +
#     geom_tile(aes(fill = time))

```

