# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

manhattan_distance_rcpp <- function(x, y) {
    .Call('_dynutils_manhattan_distance_rcpp', PACKAGE = 'dynutils', x, y)
}

