read_pseudotime <- function(dir_output) {
  pseudotime <- readr::read_csv(
    file.path(dir_output, "pseudotime.csv"),
    col_types = readr::cols(
      cell_id = readr::col_character(),
      pseudotime = readr::col_double()
    )
  ) %>%
  {set_names(.$pseudotime, .$cell_id)}
}


output_processors <- tribble(
  ~id, ~processor, ~required_files, ~description,
  "linear", function(model, dir_output) {
    pseudotime <- read_pseudotime(dir_output)
    model %>% add_linear_trajectory(pseudotime)
  }, c("pseudotime.csv"), "Creates a linear trajectory from pseudotime",

  "pseudotime", function(model, dir_output) {
    pseudotime <- read_pseudotime(dir_output)
    model %>% add_pseudotime(pseudotime)
  }, c("pseudotime.csv"), "Add pseudotime to the trajectory"
)

#' Wrap the output of a TI method
#'
#' @param model The model to start from, as generated by `wrap_data`
#' @param output_ids The ids of the outputs generated by the methods
#' @param dir_output The directory containing the output files
#'
#' @export
wrap_output <- function(model, output_ids, dir_output) {
  for (output_id in output_ids) {
    model <- output_processors$processor[[which(output_processors$id == output_id)]](model, dir_output)
  }
  model
}
