# some generic read functions
read_assignment <- function(
  path,
  col_types = readr::cols(readr::col_character(), readr::col_character())
) {
  output <- readr::read_csv(
    path,
    col_types =col_types
  )
  set_names(
    output %>% pull(2),
    output %>% pull(1)
  )
}

read_vector <- function(
  path,
  default = NULL
) {
  if(!is.null(default) && !file.exists(path)) {
    default
  } else {
    jsonlite::read_json(path) %>% unlist()
  }
}

#' Wrap the output of a TI method
#'
#' @param model The model to start from, as generated by `wrap_data`
#' @param output_ids The ids of the outputs generated by the methods
#' @param dir_output The directory containing the output files
#'
#' @export
wrap_output <- function(model, output_ids, dir_output) {
  for (output_id in output_ids) {
    model <- output_processors$processor[[which(output_processors$id == output_id)]](model, dir_output)
  }
  model
}
